export const CHUNK_EXTRACTION_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "source_summary",
    "decision_context",
    "stated_decision",
    "implied_decision",
    "goals",
    "stakeholders",
    "options_considered",
    "constraints",
    "risks",
    "assumptions",
    "evidence",
    "open_questions",
    "tensions",
    "recommendation_candidate",
    "confidence",
    "missing_context",
    "suggested_next_steps",
    "conflicts",
    "unresolved_references",
  ],
  properties: {
    source_summary: { type: "string" },
    decision_context: { type: "string" },
    stated_decision: { type: "string" },
    implied_decision: { type: "string" },
    goals: { type: "array", items: { type: "string" } },
    stakeholders: { type: "array", items: { type: "string" } },
    options_considered: { type: "array", items: { type: "string" } },
    constraints: { type: "array", items: { type: "string" } },
    risks: { type: "array", items: { type: "string" } },
    assumptions: { type: "array", items: { type: "string" } },
    evidence: { type: "array", items: { type: "string" } },
    open_questions: { type: "array", items: { type: "string" } },
    tensions: { type: "array", items: { type: "string" } },
    recommendation_candidate: { type: "string" },
    confidence: { type: "string", enum: ["High", "Medium", "Low"] },
    missing_context: { type: "array", items: { type: "string" } },
    suggested_next_steps: { type: "array", items: { type: "string" } },
    conflicts: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["topic", "statementA", "statementB"],
        properties: {
          topic: { type: "string" },
          statementA: { type: "string" },
          statementB: { type: "string" },
        },
      },
    },
    unresolved_references: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["term", "note"],
        properties: {
          term: { type: "string" },
          note: { type: "string" },
        },
      },
    },
  },
} as const;
